### PR TITLE
Added AOS on the home page

### PR DESCRIPTION
**Pull request by sumitkr2000**
## Description

Hey @AmanJain18 I have added AOS to your website. This means whenever a user scrolls the divs will animate on scroll. Please review my pr and merge it. Thank you!

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [x] The app is working correctly after applying the changes.
- [x] The app is responsive and displays properly on different screen sizes and devices.
- [x] The changes are thoroughly documented in the appropriate files or documentation sections.
- [x] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [x] I have tested the changes locally and ensured that the app is functioning as expected.
- [x] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [x] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [x] I have followed the coding conventions and style guidelines defined in the project.
- [x] I have run the automated tests and all of them pass.
- [x] I have considered the performance implications of the changes made.
- [x] I have considered the security implications of the changes made.
- [x] I have checked for any potential regressions or side effects caused by the changes.
- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

## Additional Notes(Optional)

Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues

#72 

## Reviewers

@AmanJain18

### CODE REVIEW

**Review by tusharbansal22 — APPROVED** [review]
Good work! Looks alright to me, can merge.

**Comment by tusharbansal22** [comment]
On a sidenote can we reduce the amount of animations in footer, just makes it pook less formal

**Review by AmanJain18 — COMMENTED** [review]
Looks good to me, @tusharbansal22 Just make sure that footer social icon animation are proper and giving justice...
Are there any changes to be done in animation reveal ?

**Comment by sumitkr2000** [comment]
Ok @tusharbansal22 I will remove the animations from the footer. Wait!

**Comment by sumitkr2000** [comment]
@tusharbansal22 @AmanJain18 Now check I have removed aos from the footer.

**Comment by AmanJain18** [comment]
for recent update its inside component got effect, also add the effect to title also.. as our misson and all title has got animation

**Comment by sumitkr2000** [comment]
Done bro @AmanJain18.

**Comment by sumitkr2000** [comment]
Bro i have added h2 inside the div now.

**Comment by AmanJain18** [comment]
Great Contribution @sumitkr2000

**Review by AmanJain18 — APPROVED** [review]

**Comment by sumitkr2000** [comment]
Thank you bro let me know if there are more features to be added!

**Pull request merged**
