### PR TITLE
Competitive exam section navigation and mock data added

### PR DESCRIPTION
**Pull request by Swarnavas**
## Description

I have added some mock data for the certification section. On the click of Certification button, it shows up some details.

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [ ] The app is working correctly after applying the changes.
- [ ] The app is responsive and displays properly on different screen sizes and devices.
- [ ] The changes are thoroughly documented in the appropriate files or documentation sections.
- [ ] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [ ] I have tested the changes locally and ensured that the app is functioning as expected.
- [ ] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [ ] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [ ] I have followed the coding conventions and style guidelines defined in the project.
- [ ] I have run the automated tests and all of them pass.
- [ ] I have considered the performance implications of the changes made.
- [ ] I have considered the security implications of the changes made.
- [ ] I have checked for any potential regressions or side effects caused by the changes.
- [ ] I have performed a self-review of my code.
- [ ] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [ ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ ] I ran the app and tested it locally to verify that it works as expected.

# Screenshots -
image
image

## Additional Notes(Optional)

Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues

Please list any related issues or pull requests that are associated with this pull request.

## Reviewers

Please tag the relevant team members or reviewers who should review this pull request.

### CODE REVIEW

**Comment by anmode** [comment]
I think to maintain uniformity...cards should be used....you get card component in codebase

**Comment by Swarnavas** [comment]
image

**Comment by anmode** [comment]
It looks cool! thanks..but as you can see on homepage.. we have card. so on similar basis can you design? Competetive exams liike gate, cat , ssc cgl , and other more!.

**Review by tusharbansal22 — CHANGES_REQUESTED** [review]
Use the card component used in the courses section, make the page look like courses page for standardization

**Comment by Swarnavas** [comment]
> It looks cool! thanks..but as you can see on homepage.. we have card. so on similar basis can you design? Competetive exams liike gate, cat , ssc cgl , and other more!.
> 
> How you are thinking to divide exams??
> 
> You can reuse are component for card..

I ma thinking to have list of exams with their 'Days remaining' in the right side and once you check the details of the exam, it can give you name, date, qualification, min age such things. Let me know if you think otherwise or have better ideas.

**Comment by Swarnavas** [comment]
> Use the card component used in the courses section, make the page look like courses page for standardization

That's a great suggestion. However do we have any shinning images like in Courses we have?

**Comment by anmode** [comment]
> > Use the card component used in the courses section, make the page look like courses page for standardization
> 
> That's a great suggestion. However do we have any shinning images like in Courses we have?

you can get them through freepik or online just type `gate exam vector` you will get some pics

**Comment by Swarnavas** [comment]
image

**Comment by Swarnavas** [comment]
@anmode Could you please review this.

**Review by anmode — COMMENTED** [review]
Cool! thanks @Swarnavas 
Some changes:
Could you add some resources of competetive exams after anyone click the any exams??
Please add a show effect or 3d effect to vector ( I would be very happy if you use card svg)
Increase exams please.

**Comment by anmode** [comment]
@Swarnavas ??

**Pull request closed without merging**
