### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Anikinee**
## Describe your changes
I updated the README.md file and solved the issue "New contributors not showing! In Readme "

## Screenshots - If Any (Optional)
Screenshot (387)

## Issue ticket number and link - If Any
#161 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
Please review it and let me know if any changes are to be made.

### CODE REVIEW

**Comment by anmode** [comment]
ohh! conflicts...Please resolve it

**Comment by Anikinee** [comment]
> ohh! conflicts...Please resolve it

I resolved the conflict. Please check it and let me know.

**Comment by anmode** [comment]
thanks

**Comment by Anikinee** [comment]
> thanks

Can you please add GSSOC levels in this PR (#171 ) as though it is merged but it is not included in the leaderboard? Please do it as soon as possible!!  @anmode

**Pull request merged**
