### PR TITLE
"Get In Touch With Us" Section Design Improvement

### PR DESCRIPTION
**Pull request by iamRabia-N**
## Describe your changes
I have mainly changed form's shades, background, borders, padding, margin, etc. I have mixed the properties of the CSS to make its look-and-feel even better.

## Screenshots - If Any (Optional)
Project-Amupedia ss

## Issue ticket number and link - If Any
https://github.com/amupedia2021/Project-Amupedia/issues/70

## Checklist before requesting a review
 [✓ ] I have performed a self-review of my code.
 [✓ ] Starred the repository.
 [  ] Added My Name to the Contributor's List.
 [ ✓] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
 [ ✓] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
If you want any design changes, you can specify them. I would love to consider your requirements. Also, if you like the work, I want to work on other design modules of website to create consistent design.

### CODE REVIEW

**Comment by SoundaryaKoutharapu** [comment]
Hello @iamRabia-N,
Could you please tell me how did you set up the project locally.?
and did you install any dependencies.?
could you please help me out as I am facing merge conflicts with package.json and yarn.json.

**Comment by iamRabia-N** [comment]
Hi @SoundaryaKoutharapu! 
In order to avoid errors: 
1. Reinstall node.js (in case if you have already installed). 
2. Checkout if npm installation is fine by checking its version in vs code terminal. 
3. Install yarn by command "yarn install"
4. Then run "yarn dev". 
In my case, these steps help me setup balanced and correct repo local environment for me.

**Comment by anmode** [comment]
For project setup and any issue... You can ask on the channel, please. so we can resolve it. Thanks for replying btw @iamRabia-N

**Comment by anmode** [comment]
Thanks for the contribution we will provide feedback. soon!

**Comment by SoundaryaKoutharapu** [comment]
Yeah sure @anmode, from next time onwards I'll ask in channel.

**Comment by SoundaryaKoutharapu** [comment]
> Hi @SoundaryaKoutharapu! In order to avoid errors:
> 
> 1. Reinstall node.js (in case if you have already installed).
> 2. Checkout if npm installation is fine by checking its version in vs code terminal.
> 3. Install yarn by command "yarn install"
> 4. Then run "yarn dev".
>    In my case, these steps help me setup balanced and correct repo local environment for me.

Hello @iamRabia-N ,
These steps have worked for me!
Thanks much.

**Comment by anmode** [comment]
@iamRabia-N it is optimized for mobile?

**Comment by iamRabia-N** [comment]
> @iamRabia-N it is optimized for mobile?

Yes.
Take a look at this screenshot.

img

**Comment by anmode** [comment]
great!!

**Review by anmode — APPROVED** [review]
LGTM

**Pull request merged**
