### PR TITLE
after click on hamburger icons cross icon needs to align properly #639

### PR DESCRIPTION
**Pull request by kapilG0**
## Description

previously hamburger icon not showing properly now showing properly.

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [x] The app is working correctly after applying the changes.
- [x] The app is responsive and displays properly on different screen sizes and devices.
- [ ] The changes are thoroughly documented in the appropriate files or documentation sections.
- [x] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [x] I have tested the changes locally and ensured that the app is functioning as expected.
- [x] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [ ] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [x] I have followed the coding conventions and style guidelines defined in the project.
- [ ] I have run the automated tests and all of them pass.
- [ ] I have considered the performance implications of the changes made.
- [ ] I have considered the security implications of the changes made.
- [ ] I have checked for any potential regressions or side effects caused by the changes.
- [x] I have performed a self-review of my code.
- [ ] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [ ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

## Additional Notes(Optional)

Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues

Please list any related issues or pull requests that are associated with this pull request.

## Reviewers

@Ja3mamtora Please review this pr i have fixed the issue. Thank you

### CODE REVIEW

**Comment by kapilG0** [comment]
Hello @Ja3mamtora can you please review this pr and let me know if any modifications required thank you

**Comment by Ja3mamtora** [comment]
@kapilG0 attach screenshot

**Comment by kapilG0** [comment]
> @kapilG0 attach screenshot

Hello @Ja3mamtora . Please check i am attaching screen shot 
image

**Comment by Ja3mamtora** [comment]
image
the hamburger icon is not visible

**Comment by kapilG0** [comment]
> image the hamburger icon is not visible


When I cloned that code that issue I was also getting but if you will click on right top you will see list and cross icon. I need to check why it is happening but cross icon has fixed please click on top right corner

**Comment by kapilG0** [comment]
Hello @Ja3mamtora i have fixed that issue also as you told hamburger not visible https://github.com/amupedia2021/amupedia-web/pull/642/commits/cca69e8449e5635ac7c11e23a345014cae40a736 this is pull request . please check

**Comment by kapilG0** [comment]
Hello @Ja3mamtora i have fixed that now' icon is showing please check and let me know if any modifications required

**Comment by kapilG0** [comment]
Hello @Ja3mamtora i have fixed that now' icon is showing please check and let me know if any modifications required

**Pull request merged**
