### PR TITLE
Create Opportunity Detail Backend

### PR DESCRIPTION
**Pull request by SayyidMuhammad878**
## Describe your changes
Create Opportunity Detail Backend

### Here is the demo:
https://drive.google.com/file/d/1s309oLzZ0hnaAhoAlzOzkyV4PUEGDN10/view?usp=sharing

### CODE REVIEW

**Review by sayyedarib — APPROVED** [review]

**Comment by anmode** [comment]
Please! Try to find out to solve this linting problem in the codebase....as Preterier tries to format code and those changes are scrapped.

**Comment by anmode** [comment]
there are conflicts! As Arib PR merged recently....Please resolve them all @SayyidMuhammad878

**Comment by SayyidMuhammad878** [comment]
> there are conflicts! As Arib PR merged recently....Please resolve them all @SayyidMuhammad878

I've fixed the conflicts

**Comment by anmode** [comment]
Great!

**Pull request merged**
