### PR TITLE
Added meta tags

### PR DESCRIPTION
**Pull request by Avinash905**
## Description

Added meta tags like title tag, keywords, language, author, robots, revisit-after

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [x] The app is working correctly after applying the changes.
- [x] The app is responsive and displays properly on different screen sizes and devices.
- [x] The changes are thoroughly documented in the appropriate files or documentation sections.
- [x] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [x] I have tested the changes locally and ensured that the app is functioning as expected.
- [x] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [x] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [x] I have followed the coding conventions and style guidelines defined in the project.
- [x] I have run the automated tests and all of them pass.
- [x] I have considered the performance implications of the changes made.
- [x] I have considered the security implications of the changes made.
- [x] I have checked for any potential regressions or side effects caused by the changes.
- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [x] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

## Related Issues

#523

### CODE REVIEW

**Comment by Harshil-Jani** [comment]
@Avinash905 Does having meta tags even in different pages like `about.js` and `contributors/index.js` helps in increasing visiblity of individual pages ? If it helps then please do add them there too. This would be really helpful for us. Thanks.

**Comment by Avinash905** [comment]
> @Avinash905 Does having meta tags even in different pages like `about.js` and `contributors/index.js` helps in increasing visiblity of individual pages ? If it helps then please do add them there too. This would be really helpful for us. Thanks.

The same meta tags in _app.js will reflect on all other pages too. But if we add any meta tag to other pages then it will replace that tag from _app.js.

For example: In _app.js the value of the title tag is Project-Amupedia then all the other pages will have the same title. But if we add some other title tag like Project-Amupedia-About in about.js then only that title tag will be replaced rest others will be same

**Review by Harshil-Jani — APPROVED** [review]

**Comment by Harshil-Jani** [comment]
> The same meta tags in _app.js will reflect on all other pages too. But if we add any meta tag to other pages then it will replace that tag from _app.js.
> 
> For example: In _app.js the value of the title tag is Project-Amupedia then all the other pages will have the same title. But if we add some other title tag like Project-Amupedia-About in about.js then only that title tag will be replaced rest others will be same

Cool !! Thanks.

**Comment by Avinash905** [comment]
@anmode @Harshil-Jani Could you please add the level label?

**Pull request merged**
