### PR TITLE
Add JS Validation on Contact Us form

### PR DESCRIPTION
**Pull request by Geeta259**
issue #479 

## Pull Request Checklist

Add empty validation on contact form
Validation add for valid email
Error message shown below of each fields
Highlighted that field by red border to enhance user experience.
Show success message after submit form.

Please make sure that your PR meets the following requirements:

- [x ] The app is working correctly after applying the changes.
- [ x] The app is responsive and displays properly on different screen sizes and devices.
- [ ] The changes are thoroughly documented in the appropriate files or documentation sections.
- [ x] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [ x] I have tested the changes locally and ensured that the app is functioning as expected.
- [ x] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [ x] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [ ] I have followed the coding conventions and style guidelines defined in the project.
- [ x] I have run the automated tests and all of them pass.
- [ x] I have considered the performance implications of the changes made.
- [ x] I have considered the security implications of the changes made.
- [ ] I have checked for any potential regressions or side effects caused by the changes.
- [ ] I have performed a self-review of my code.
- [x ] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [ ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ ] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

Screenshot (619)
Screenshot (620)
Screenshot (621)
Screenshot (622)
Screenshot (623)
Screenshot (624)

@Aarav238  Please check this PR linked with issue#479

### CODE REVIEW

**Comment by Aarav238** [comment]
Great Work @Geeta259 . Thanks. 
Please look on other issues as well.

**Comment by Geeta259** [comment]
> Great Work @Geeta259 . Thanks. Please look on other issues as well.

Thanks!! Please add appropriate level on this PR.

**Comment by Geeta259** [comment]
@Aarav238 kindly request please add appropriate level label on this PR.🙂

**Comment by Geeta259** [comment]
@anmode @tayyab-ilyas Please add appropriate level label on this PR.

**Pull request merged**
