### PR TITLE
added coming soon page

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## 
Screenshot 2023-05-20 at 23 22 23

https://github.com/amupedia2021/Project-Amupedia/assets/91741581/3d875961-7dcf-4c26-b98c-912d7d4535c5

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [x] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

### CODE REVIEW

**Comment by anmode** [comment]
i have added to my review. will review soon thanks

**Comment by Vidip-Ghosh** [comment]
> i have added to my review list. will review soon thanks

Here it is showing that the branch has conflicts but Resolve Conflict option is disabled. How can I solve?

**Comment by anmode** [comment]
try to resolve conflicts at your local. pull the new commits and there conflicts will come to your local too. resolve those and push.https://www.simplilearn.com/tutorials/git-tutorial/merge-conflicts-in-git

**Comment by Vidip-Ghosh** [comment]
Hi @anmode I have solved the merge conflicts.

**Comment by anmode** [comment]
congrats!!

**Comment by AmanJain18** [comment]
> congrats!!

I didn't like the UI, I have better update Fix ?

**Pull request merged**
