### PR TITLE
Search Bar to Contributors (vaibhav-xt)

### PR DESCRIPTION
**Pull request by vaibhav-xt**
## Description
The search bar is working correctly. 

Please provide a brief description of the changes introduced in this pull request. Explain the problem you are solving or the feature you are adding.

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [X] The app is working correctly after applying the changes.
- [X] The app is responsive and displays properly on different screen sizes and devices.
- [X] The changes are thoroughly documented in the appropriate files or documentation sections.
- [X] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [X] I have tested the changes locally and ensured that the app is functioning as expected.
- [X] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [X] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [X] I have followed the coding conventions and style guidelines defined in the project.
- [X] I have run the automated tests and all of them pass.
- [X] I have considered the performance implications of the changes made.
- [X] I have considered the security implications of the changes made.
- [X] I have checked for any potential regressions or side effects caused by the changes.
- [X] I have performed a self-review of my code.
- [X] Starred the repository.
- [X] Added My Name to the Contributor's List.
- [X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [X] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)
Screenshot (3)

Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues
issue #468 

Please list any related issues or pull requests that are associated with this pull request.

## Reviewers

Please tag the relevant team members or reviewers who should review this pull request.

### CODE REVIEW

**Comment by vaibhav-xt** [comment]
> @vaibhav-xt Thanks a lot for this PR. But currently what happens is that you can search a user only on a single page. For Example, If user is on 2nd page then you cannot return it from the first page. We would want this to be searched across all the pages.

Right, but the I have to give per_page= 100 so that I can fetch all users.

**Comment by Harshil-Jani** [comment]
@vaibhav-xt I am afraid that being a good solution. I would suggest that you create another function where there is no per page attribute and it returns all the list of contributors. Then store them in state variable just like `contributors` so maybe call it `allContributors`. Now for your filtering if someone searches then apply the filter on allContributors and make it conditional call if the input field is empty it calls what we have right now with per page i.e `contributors` array state variable. And if it is not empty which basically means a user is calling a query, Then return it from `allContributors`.

Let me know your thoughts on this.

**Comment by vaibhav-xt** [comment]
Oh, I was working on this idea and now it's fixed and working great.

**Comment by Harshil-Jani** [comment]
@vaibhav-xt  Pretty Awesome. Thanks a lot for this feature. 💯

**Pull request merged**
