### PR TITLE
black Image added for None-existing User

### PR DESCRIPTION
**Pull request by PrakashGatiyala**
Signed-off-by: Prakash <gatiyalap@gmail.com>

## Describe your changes
Hi, I have added black-image for none existing user in Image folder. 
Since the test branch is behind of master branch.(Team information is not there in test branch). So I didn't added any code for this. 
## Issue ticket number and link - If Any
https://github.com/amupedia2021/Project-Amupedia/issues/36
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] Starred the repository.
- [X] Added My Name to the Contributor's List.
- [X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [X] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
Any additional information that you want to give us

### CODE REVIEW

**Comment by PrakashGatiyala** [comment]
Hi @anmode , I have add the code in latest commit.([4c04721](https://github.com/amupedia2021/Project-Amupedia/pull/37/commits/4c047213a0a2fde3cfd6cd8842eaf1494e79a1a8))
Now it will show like this. Can you review it and merge it. 
image

**Comment by anmode** [comment]
> Hi @anmode , I have add the code in latest commit.([4c04721](https://github.com/amupedia2021/Project-Amupedia/pull/37/commits/4c047213a0a2fde3cfd6cd8842eaf1494e79a1a8))
> Now it will show like this. Can you review it and merge it. 
> image
> 
> 
> 

Hii! You have just added a black img...
But this commit will be reverted by us when we add team member pic.
I hope you understand. I can't merge.

**Comment by PrakashGatiyala** [comment]
I thought  you agreed for this. 

image

**Comment by anmode** [comment]
> I thought  you agreed for this. 
> 
> image
> 

Actually i misunderstood...i though you will be doing changes with css. But you added a black img.

**Comment by PrakashGatiyala** [comment]
> > Hi @anmode , I have add the code in latest commit.([4c04721](https://github.com/amupedia2021/Project-Amupedia/pull/37/commits/4c047213a0a2fde3cfd6cd8842eaf1494e79a1a8))
> > Now it will show like this. Can you review it and merge it.
> > image
> 
> Hii! You have just added a black img... But this commit will be reverted by us when we add team member pic. I hope you understand. I can't merge.
You don't actually need to revert this commit though.  You can update it later though, when you get member image.

**Comment by PrakashGatiyala** [comment]
> > I thought  you agreed for this.
> > image
> 
> Actually i misunderstood...i though you will be doing changes with css. But you added a black img.

Oh, you want me to change CSS, I can do that as well.

**Comment by anmode** [comment]
> > > I thought  you agreed for this.
> > > image
> > 
> > Actually i misunderstood...i though you will be doing changes with css. But you added a black img.
> 
> Oh, you want me to change CSS, I can do that as well. 

Btw could you please focus on another issues...
As i think we need no change as our team page will be updated soon.

**Comment by PrakashGatiyala** [comment]
okay

**Comment by anmode** [comment]
> okay

Thanks!

**Pull request closed without merging**
