### PR TITLE
Added Competitive Exam Section with Tables, Images, and Exam Details

### PR DESCRIPTION
**Pull request by Nishitbaria**
Issue #456 

## Description
This pull request introduces a new section in the repository for competitive exams. I have added relevant content using tables and images to enhance the presentation of information. Additionally, I have structured the data using a JSON array with an examDetails field to provide a standardized format for displaying details of various exams.
Changes Made:
-added relevant content for each exam
- Added tables to display information about each exam, making it more organized and easily readable.
- Incorporated relevant images related to the exams to provide visual context.
- Introduced a JSON array `examDetails` to maintain uniformity in displaying exam details.
- Populated the array with detailed information for various exams, including name, conducting body, level, application mode, exam frequency, etc.

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [x] The app is working correctly after applying the changes.
- [x] The app is responsive and displays properly on different screen sizes and devices.
- [ ] The changes are thoroughly documented in the appropriate files or documentation sections.
- [ ] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [x] I have tested the changes locally and ensured that the app is functioning as expected.
- [ ] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [x] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [ ] I have followed the coding conventions and style guidelines defined in the project.
- [ ] I have run the automated tests and all of them pass.
- [x] I have considered the performance implications of the changes made.
- [ ] I have considered the security implications of the changes made.
- [ ] I have checked for any potential regressions or side effects caused by the changes.
- [ ] I have performed a self-review of my code.
- [ ] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [ ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ ] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)
image

https://github.com/amupedia2021/Project-Amupedia/assets/85815172/781eed01-8450-4275-acb9-02cb94a6f55a

Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues

Please list any related issues or pull requests that are associated with this pull request.

## Reviewers

@anmode @tayyab-ilyas  please review and merge my pull request

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@anmode @tayyab-ilyas please review and merge my pull request

**Comment by Nishitbaria** [comment]
@anmode @tayyab-ilyas please review and merge my pull request

**Comment by Nishitbaria** [comment]
@tayyab-ilyas  @anomde any other issues i can work on?

**Comment by tayyab-ilyas** [comment]
> @tayyab-ilyas @anomde any other issues i can work on?

try this #368 @Nishitbaria

**Pull request merged**
