### PR TITLE
Added Relevant Content to Blog Section and Fixed Dynamic Route Refreshing Issue

### PR DESCRIPTION
**Pull request by Nishitbaria**
**Related Issue:(#465)**

## Description

Please provide a brief description of the changes introduced in this pull request. Explain the problem you are solving or the feature you are adding.

**Changes Made:**
- Added relevant content to the blog section.
- Added content for specific blog pages.
- Solved the issue of refreshing problem on dynamic routes of the blog.

**Details:**
- Updated the blog section by adding informative and engaging content to improve user experience and provide valuable information to readers.
- Created new blog pages with detailed content for specific topics, enhancing the blog's diversity and addressing various interests.
- Resolved the refreshing problem occurring on dynamic routes of the blog. Previously, the page did not refresh properly when navigating between different blog posts or when the URL changed dynamically. Implemented a fix to ensure smooth and accurate page refreshes, allowing users to seamlessly browse the blog without any disruptions.

**Technical Changes:**
- Modified the blog section's code files to include the new content.
- Created separate markdown files for the new blog pages and added relevant content to each file.
- Implemented a solution to fix the refreshing issue on dynamic routes. This may involve updating the routing logic, handling URL changes properly, and ensuring that the page content is dynamically loaded and refreshed when needed.

## Screenshotts

image

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [x] The app is working correctly after applying the changes.
- [ ] The app is responsive and displays properly on different screen sizes and devices.
- [ ] The changes are thoroughly documented in the appropriate files or documentation sections.
- [ ] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [x] I have tested the changes locally and ensured that the app is functioning as expected.
- [ ] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [ ] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [x] I have followed the coding conventions and style guidelines defined in the project.
- [ ] I have run the automated tests and all of them pass.
- [x] I have considered the performance implications of the changes made.
- [ ] I have considered the security implications of the changes made.
- [ ] I have checked for any potential regressions or side effects caused by the changes.
- [ ] I have performed a self-review of my code.
- [ ] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

## Additional Notes(Optional)

Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues

Please list any related issues or pull requests that are associated with this pull request.

## Reviewers

Please tag the relevant team members or reviewers who should review this pull request.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@anmode ,please review my pull request

**Comment by Nishitbaria** [comment]
And  
I have successfully understood the backend process of creating and fetching blogs. Currently, I am implementing this functionality using JSON data. However, I have identified an opportunity to enhance the blog creation experience for authors.

In order to improve the efficiency and user-friendliness of the blog creation process, I plan to create an issue where I will introduce a functionality that allows authors to create blogs using a markdown editor. This markdown editor will enable authors to format their blog content easily and provide a more seamless experience for blog creation.

I believe this addition will greatly enhance the overall functionality and usability of our blog section. I will create the issue shortly and provide more details regarding the implementation.

**Comment by Nishitbaria** [comment]
See video
https://github.com/amupedia2021/Project-Amupedia/assets/85815172/be88dfe2-36b1-44eb-ae1d-b7b6512f975c

**Comment by tayyab-ilyas** [comment]
Nice Work!

**Comment by tayyab-ilyas** [comment]
> And I have successfully understood the backend process of creating and fetching blogs. Currently, I am implementing this functionality using JSON data. However, I have identified an opportunity to enhance the blog creation experience for authors.
> 
> In order to improve the efficiency and user-friendliness of the blog creation process, I plan to create an issue where I will introduce a functionality that allows authors to create blogs using a markdown editor. This markdown editor will enable authors to format their blog content easily and provide a more seamless experience for blog creation.
> 
> I believe this addition will greatly enhance the overall functionality and usability of our blog section. I will create the issue shortly and provide more details regarding the implementation.

You can create an issue for this as well

**Pull request merged**
