### PR TITLE
Update Testimonial Image Section

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Description
- **`Update  Image Option in data.json and testimonial.js in Testimonial Component attached with Testimonial Message, Testimonial Name and Testimonial Role`**
- **Added Profile-person Icon in separate testimonialImg Sub-Folder in Images Parent Folder**
- **That added Image placed in image key section in data.json File** 

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [x] The app is working correctly after applying the changes.
- [x] The app is responsive and displays properly on different screen sizes and devices.
- [x] The changes are thoroughly documented in the appropriate files or documentation sections.
- [x] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [x] I have tested the changes locally and ensured that the app is functioning as expected.
- [x] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [ ] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [x] I have followed the coding conventions and style guidelines defined in the project.
- [ ] I have run the automated tests and all of them pass.
- [x] I have considered the performance implications of the changes made.
- [ ] I have considered the security implications of the changes made.
- [x] I have checked for any potential regressions or side effects caused by the changes.
- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ ] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

## Additional Notes(Optional)

Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues

Please list any related issues or pull requests that are associated with this pull request.
Closes Issue No < #434 >

## Reviewers
**Please Check and Review my Pull Request with adding Images @anmode and add Respective Label Levels.**

### CODE REVIEW

**Comment by Harshil-Jani** [comment]
@NarendraKoya999 Hey sorry for the late review. 
As I can see on the site. It doesn't look pretty.  I would suggest you to add a dummy photo instead of keeping the strings blank since it just made it look unattractive as in screenshot below.

image

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 Hey sorry for the late review. 
> As I can see on the site. It doesn't look pretty.  I would suggest you to add a dummy photo instead of keeping the strings blank since it just made it look unattractive as in screenshot below.
> 
> image
> 

Ok @Harshil-Jani

**Comment by NarendraKoya999** [comment]
@Harshil-Jani . With your Suggested Changes, I made that work related to this PR. But, Website has Lazy Loading and CSS Conflicts Problems. I will try again and again and that Profile Image not visible along with Testimonial Name and Testimonial Role

**Comment by NarendraKoya999** [comment]
Hi @Harshil-Jani . Please Give Me Update about this PR?

**Pull request closed without merging**
