### PR TITLE
Issue 338

### PR DESCRIPTION
**Pull request by Priy002**
## Description

This pull request introduces a dropdown menu to the "Courses" link in the navigation bar, enhancing the user experience by providing direct access to specific courses.

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [ x] The app is working correctly after applying the changes.
- [x ] The app is responsive and displays properly on different screen sizes and devices.
- [x ] The changes are thoroughly documented in the appropriate files or documentation sections.
- [x ] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [x ] I have tested the changes locally and ensured that the app is functioning as expected.
- [x ] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [x ] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [x ] I have followed the coding conventions and style guidelines defined in the project.
- [ x] I have run the automated tests and all of them pass.
- [x ] I have considered the performance implications of the changes made.
- [x ] I have considered the security implications of the changes made.
- [x ] I have checked for any potential regressions or side effects caused by the changes.
- [x ] I have performed a self-review of my code.
- [ x] Starred the repository.
- [x ] Added My Name to the Contributor's List.
- [ x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x ] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)
image

## Additional Notes(Optional)

Changes Made:
Added necessary state and event handlers to manage the visibility of the dropdown menu.
Modified the "Courses" link to trigger the opening and closing of the dropdown menu on hover.
Implemented the dropdown menu as a nested ul element, populated with individual course links.
Handled dropdown item selection by implementing appropriate event handlers.

## Related Issues

Please list any related issues or pull requests that are associated with this pull request.

## Reviewers
@AmanJain18  @anmode

Please tag the relevant team members or reviewers who should review this pull request.

https://github.com/amupedia2021/Project-Amupedia/assets/73902900/ff53c061-bd95-4865-af64-2a665b81c093

### CODE REVIEW

**Comment by AmanJain18** [comment]
And what about the small devices ? is it responsive?

**Comment by AmanJain18** [comment]
@Priy002 Greta PR, we will merge this later, as we are planning to roll out new update and all, it would be appropriate to merger these PR at that time...

**Comment by Priy002** [comment]
It is responsive.

**Review by anmode — COMMENTED** [review]
I really like the design!  I need one card like this in grabtern. 
but Let's talk about this-

It is not responsive I and aman have a convo and decide this - while @AmanJain18 has another idea too!

https://github.com/amupedia2021/Project-Amupedia/assets/88332977/e8992c8b-a16d-4ad6-9393-1c8d73ae1309

**Comment by Priy002** [comment]
Oh, sorry about that, I'll check and it will be responsive by today.
Where do you want this design implement in Grabtern?
I can work on that.

**Comment by anmode** [comment]
> Oh, sorry about that, I'll check and it will be responsive by today. Where do you want this design implement in Grabtern? I can work on that.

When you go to Grabtern click on login.... there I want the card. but one contributor is working. I think you may help her.

**Comment by Priy002** [comment]
Changes done!
image

https://github.com/amupedia2021/Project-Amupedia/assets/73902900/d2620b22-fd4a-4e4c-a716-6eea9691c314

**Comment by Priy002** [comment]
Okay, I'll help her; can you give me contributor's user ID so i can get in touch

**Comment by Priy002** [comment]
> > Changes done! image
> > dropdownResponsive.mp4
> 
> oh no no!! First of all, remove the hover in the phone.. so the user can click and another box can come... please keep the box at the left of course... I think you get that. For now, remove your functionality in mobile mode...! it looks cool in desktop mode

okay, got it!

**Comment by anmode** [comment]
> Okay, I'll help her; can you give me contributor's user ID so i can get in touch

see this pR : https://github.com/anmode/grabtern-frontend/pull/229

**Comment by anmode** [comment]
Some changes needed otherwise LGTM:
Screenshot 2023-06-03 at 2 23 47 PM. 
Screenshot 2023-06-03 at 2 23 57 PM

It looks good but see there is overlay in original i think you removed that.


and other thing is-
Screenshot 2023-06-03 at 2 24 05 PM

courses keep glowing but we aren't on course section!

**Comment by Priy002** [comment]
Check this out!

https://github.com/amupedia2021/Project-Amupedia/assets/73902900/15c11a21-97e7-422b-8289-991ffe4e2646

**Comment by AmanJain18** [comment]
And what about the overlay in the mobile view when Additional courses div open up.
Check once

**Comment by Priy002** [comment]
> And what about the overlay in the mobile view when Additional courses div open up. Check once

Fixed the overlay part of the code too, I guess it'll work.
If im missing your point please elaborate little more how it should look in mobile view.

**Comment by AmanJain18** [comment]
LGTM, tomorrow we will discuss with u on vc in discord.

**Comment by Priy002** [comment]
> LGTM, tomorrow we will discuss with u on vc in discord.

Hey, what's next?

**Review by anmode — COMMENTED** [review]
Needs some changes.. Btw it is cool @Priy002

**Comment by anmode** [comment]
https://github.com/amupedia2021/Project-Amupedia/assets/88332977/3813c174-c3d9-4ba2-9d1c-9e20aadc5cc2

To be fix-
1. There should be an overlay when we open the side menu ( see I'll attact vedio of nav menu now)
2. When we click on courses in mobile mode anchor to be removed as when we click on courses it redirect to courses with the other side menu
3. I try to show both menus open up and closes simultaneously
4. when we click anywhere into the window menu should close by itself

if you want a google meet to explain. please ping me in Discord thanks


nav menu now:

https://github.com/amupedia2021/Project-Amupedia/assets/88332977/0247c6b3-58d6-45f5-b405-4f64343a9926

**Comment by Priy002** [comment]
> navnow.mp4 
> To be fix-
> 
> 1. There should be an overlay when we open the side menu ( see I'll attact vedio of nav menu now)
> 2. When we click on courses in mobile mode anchor to be removed as when we click on courses it redirect to courses with the other side menu
> 3. I try to show both menus open up and closes simultaneously
> 4. when we click anywhere into the window menu should close by itself
> 
> if you want a google meet to explain. please ping me in Discord thanks
> 
> nav menu now:
> 
>  nav.mp4

Gmeet will be more effective i'll ping you

**Comment by Priy002** [comment]
> Needs some changes.. Btw it is cool @Priy002

Thanks! I'm having fun working on it!

**Comment by Priy002** [comment]
> navnow.mp4 
> To be fix-
> 
> 1. There should be an overlay when we open the side menu ( see I'll attact vedio of nav menu now)
> 2. When we click on courses in mobile mode anchor to be removed as when we click on courses it redirect to courses with the other side menu
> 3. I try to show both menus open up and closes simultaneously
> 4. when we click anywhere into the window menu should close by itself
> 
> if you want a google meet to explain. please ping me in Discord thanks
> 
> nav menu now:
> 
>  nav.mp4


Is it correct now?

https://github.com/amupedia2021/Project-Amupedia/assets/73902900/ccac6f54-0ce9-4289-98e6-c711416c960d

**Review by anmode — APPROVED** [review]
cool, Great. Thanks @Priy002 .
I took time to get review. I apologize. I was busy with grabtern. Hoping to get nice contribution from your side.

**Comment by Priy002** [comment]
> cool, Great. Thanks @Priy002 . I took time to get review. I apologize. I was busy with grabtern. Hoping to get nice contribution from your side.

yeah, sure!

**Comment by anmode** [comment]
@Priy002 : https://github.com/anmode/grabtern-frontend/issues

**Pull request merged**
