### PR TITLE
Added React-Toastify

### PR DESCRIPTION
**Pull request by Shahil093**
#504

Added Toast Notifications Feature
Description
Implemented the toast notifications feature using the react-toastify library. Toast notifications are displayed for various events in the application, including form validation errors, success messages, and error messages.

Changes Made
Imported the necessary components from the react-toastify library. Added toast notifications for form validation errors in the login form. Added toast notifications for login success and failure messages. Utilized the ToastContainer component to render the toast notifications.

## Description

Please provide a brief description of the changes introduced in this pull request. Explain the problem you are solving or the feature you are adding.

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [x] The app is working correctly after applying the changes.
- [x] The app is responsive and displays properly on different screen sizes and devices.
- [x] The changes are thoroughly documented in the appropriate files or documentation sections.
- [x] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [x] I have tested the changes locally and ensured that the app is functioning as expected.
- [x] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [x] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [x] I have followed the coding conventions and style guidelines defined in the project.
- [x] I have run the automated tests and all of them pass.
- [x] I have considered the performance implications of the changes made.
- [x] I have considered the security implications of the changes made.
- [x] I have checked for any potential regressions or side effects caused by the changes.
- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [x] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

## Additional Notes(Optional)

Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues

Please list any related issues or pull requests that are associated with this pull request.

## Reviewers

Please tag the relevant team members or reviewers who should review this pull request.

### CODE REVIEW

**Comment by Shahil093** [comment]
Screenshot (160)

**Comment by Shahil093** [comment]
,

**Review by Shahil093 — COMMENTED** [review]
Why my vercel deployment failed here?

**Comment by Shahil093** [comment]
.

**Comment by anmode** [comment]
error:
```


./pages/index.js:105:24
--
17:18:18.163 | Syntax error: Unexpected reserved word 'await'.
17:18:18.163 |  
17:18:18.163 | 103 \|           setLoading(true);
17:18:18.163 | 104 \|           try {
17:18:18.163 | > 105 \|             const res = await axios.post('/api/submitForm', form);
17:18:18.163 | \|                         ^
17:18:18.164 | 106 \|             const data = await res.data;
17:18:18.164 | 107 \|             console.log(data);
17:18:18.165 | 108 \|             dispatch({
17:18:18.165 |  
17:18:18.165 |  
17:18:18.165 | > Build failed because of webpack errors
17:18:18.204 | error Command failed with exit code 1.
17:18:18.205 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
17:18:18.230 | Error: Command "yarn run build" exited with 1


```

**Pull request closed without merging**
