### PR TITLE
Adding cse 1st sem notes

### PR DESCRIPTION
**Pull request by MohammadAsiya**
ADDING CSE 1 ST SEM NOTES #124 
In B.tech computer science 1 st sem notes is not available. So I am added 1sem notes.
In this notes 5 subjects are available. 
They are C programming, Mathematics,  Engineering Physics, Engineering Chemistry, Basic Electrical and Electronics Engineering.

Please review and merge to the main branch.

This issue is assigned to me under GSSOC2023. This issue number is #124 
## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [X ] The app is working correctly after applying the changes.
- [X ] The app is responsive and displays properly on different screen sizes and devices.
- [ X] The changes are thoroughly documented in the appropriate files or documentation sections.
- [X ] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [ X] I have tested the changes locally and ensured that the app is functioning as expected.
- [ X] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [X ] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [X ] I have followed the coding conventions and style guidelines defined in the project.
- [ X] I have run the automated tests and all of them pass.
- [ X] I have considered the performance implications of the changes made.
- [ X] I have considered the security implications of the changes made.
- [ X] I have checked for any potential regressions or side effects caused by the changes.
- [ X] I have performed a self-review of my code.
- [X ] Starred the repository.
- [ X] Added My Name to the Contributor's List.
- [ X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ X] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

## Additional Notes(Optional)

Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues

Please list any related issues or pull requests that are associated with this pull request.

## Reviewers

Please tag the relevant team members or reviewers who should review this pull request.
#Anmol Agrawal

### CODE REVIEW

**Comment by tusharbansal22** [comment]
I am afraid but we cant count that as a direct contribution, also, I would recommend to create an issue first, get it approved by mentors and then go about to create a PR. We are thinking of how to manage the notes issue, any good idea will be welcomed. Closing for now @MohammadAsiya

**Comment by MohammadAsiya** [comment]
This issue is assigned to me . That issue no is 124.

**Comment by tusharbansal22** [comment]
Oh my bad then. @anmode will have a better say at this.

**Comment by anmode** [comment]
@MohammadAsiya could you please look other issues? some technical one..which will enhace your dev too please?

**Comment by MohammadAsiya** [comment]
Sure,I will do that.

**Comment by MohammadAsiya** [comment]
Thank you.

**Pull request merged**
