### PR TITLE
Sitemap Addition #297

### PR DESCRIPTION
**Pull request by NikhilRaikwar**
## Description

This pull request aims to address the issue of the missing sitemap in the repository. By adding a sitemap to the website, we can improve search engine visibility and enhance user navigation. The sitemap will provide a comprehensive list of all the website's pages, enabling search engine crawlers to index and rank them effectively. Additionally, users will benefit from a more organized and user-friendly browsing experience.

Issue #297 

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [✅ ] The app is working correctly after applying the changes.
- [✅ ] The app is responsive and displays properly on different screen sizes and devices.
- [✅ ] The changes are thoroughly documented in the appropriate files or documentation sections.
- [✅ ] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [✅ ] I have tested the changes locally and ensured that the app is functioning as expected.
- [✅ ] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [✅ ] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [✅ ] I have followed the coding conventions and style guidelines defined in the project.
- [✅ ] I have run the automated tests and all of them pass.
- [✅ ] I have considered the performance implications of the changes made.
- [ ✅] I have considered the security implications of the changes made.
- [ ✅] I have checked for any potential regressions or side effects caused by the changes.
- [✅ ] I have performed a self-review of my code.
- [✅ ] Starred the repository.
- [✅ ] Added My Name to the Contributor's List.
- [✅ ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [✅ ] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

## Additional Notes(Optional)

In this pull request, I have created a new sitemap file in XML format, incorporating all the URLs of the website's pages.

## Related Issues

N/A
## Reviewers

@AmanJain18

### CODE REVIEW

**Review by AmanJain18 — CHANGES_REQUESTED** [review]
- Also Add <changefreq>daily</changefreq> for homepage and contributors and weekly for rest url
- I guess Robots.txt can have few more bots and naming of some UA is not appropriate.

**Comment by NikhilRaikwar** [comment]
Ok I will update the files.

**Comment by AmanJain18** [comment]
should i provide robots.txt ?

**Comment by NikhilRaikwar** [comment]
Implemented requested changes: added proper UA names, updated sitemap with daily/weekly frequencies. Pls Review.

**Review by AmanJain18 — APPROVED** [review]
check discord Dm

**Pull request merged**
