### PR TITLE
ADD : formsubmit service

### LINKED ISSUE #340: 🚀 [Feature Request] - Integrating contact us form with formsubmit.co
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

The feature request is related to the contact us form

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
- we would use formsubmit.co to direct all the data collected from the form to your email
```

### Additional context or screenshots

And FYI , the services of formsubmit.co are free.
**`NOTE`** - **Please Provide the email where all data will be delivered**

For reference visit - https://www.krashish.live/contact

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

### PR DESCRIPTION
**Pull request by dev-AshishRanjan**
## Description

The contact form has been linked to formsubmit.co 

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [X] The app is working correctly after applying the changes.
- [X] The app is responsive and displays properly on different screen sizes and devices.
- [X] The changes are thoroughly documented in the appropriate files or documentation sections.
- [X] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [X] I have tested the changes locally and ensured that the app is functioning as expected.
- [X] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [ ] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [X] I have followed the coding conventions and style guidelines defined in the project.
- [X] I have run the automated tests and all of them pass.
- [X] I have considered the performance implications of the changes made.
- [X] I have considered the security implications of the changes made.
- [X] I have checked for any potential regressions or side effects caused by the changes.
- [X] I have performed a self-review of my code.
- [X] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [X] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

## Additional Notes(Optional)

The URL is incomplete, 
In pages->index.js , on line 76 use the desired email in place of {Enter Email}
`{Enter Email}` to `example@gmail.com`

***NOTE***
**When you use formsubmit for the first time from a new domain, you have to give access to your email.**
***Simply when you first submit the form, on the given email, a new mail will come asking for cinfirmation, that's it***

## Related Issues
closes #340 

## Reviewers
@AmanJain18

### CODE REVIEW

**Comment by AmanJain18** [comment]
@dev-AshishRanjan Which file is this pnpn

**Comment by dev-AshishRanjan** [comment]
> @dev-AshishRanjan Which file is this pnpn

It's the auto generated lock file for pnpm just like package-lock.json, when you run `pnpm i`
In the second commit I tried to put it in `.gitignore`

**Comment by dev-AshishRanjan** [comment]
Should I delete that file, it's actually not required

**Comment by AmanJain18** [comment]
@dev-AshishRanjan Ya delete it. if not needed

**Comment by anmode** [comment]
```
6:52:20 AM: npm ERR! code EUNSUPPORTEDPROTOCOL
6:52:20 AM: npm ERR! Unsupported URL Type "link:": link:dummy.js
6:52:20 AM: npm ERR! A complete log of this run can be found in:
6:52:20 AM: npm ERR!     /opt/buildhome/.npm/_logs/2023-06-06T01_19_54_307Z-debug-0.log
6:52:20 AM: Error during npm install
6:52:20 AM: Build was terminated: dependency_installation script returned non-zero exit code: 1
6:52:21 AM: Failing build: Failed to install dependencies
6:52:21 AM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
```

**Comment by dev-AshishRanjan** [comment]
Hi @anmode ,
I didn't do any other code changes except for the index.js
So I am not finding why the error is occuring.

So I created a new PR 392, where this error is not occuring.
Maybe it was result of pnpm-lock

**Comment by AmanJain18** [comment]
@dev-AshishRanjan Closing this pr then

**Pull request closed without merging**
