### PR TITLE
added  new branch ie ECE-AI

### PR DESCRIPTION
**Pull request by anjaliSilawat**
added  new branch called ECE-AI and its resources 
#148 resolve 
@anmode please approve this and merge it 😊

### CODE REVIEW

**Comment by AmanJain18** [comment]
Ece means electronics only na ?
Electronic ke toh block card already hai...

**Comment by anjaliSilawat** [comment]
> Ece means electronics only na ? Electronic ke toh block card already hai...

no no its not ece , mene jo bnaya hai vo ece-ai hai i.e Electronics and Communication Engineering (ECE) with a specialization in Artificial Intelligence @AmanJain18

**Comment by AmanJain18** [comment]
Ok, great addition, will have to keep on hold for rn, due to backend work going on.. hope u will understand.

**Review by anmode — APPROVED** [review]

**Comment by anmode** [comment]
Hey @anjaliSilawat Thank you so much for providing the notes.

**Comment by anjaliSilawat** [comment]
> Ok, great addition, will have to keep on hold for rn, due to backend work going on.. hope u will understand.

Oh so @AmanJain18 How much time will it take for you to accept my PR

**Comment by anjaliSilawat** [comment]
Idk why but in the assignees section it shows “no one assigned "  @anmode

**Pull request merged**
