### PR TITLE
Logo on home page

### LINKED ISSUE #419: 🚀 [Feature Request] - Adding Logo to website
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement

### Describe briefly how you would implement this enhancement.

```bash
Some steps to implement this enhancement-
1. Step 1 Making a logo for the website 
2. Step 2 Adding it to home page along Nav bar on top left corner.
```

### Additional context or screenshots

_No response_

### Are you contributing for a program?

GSSoC2023

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

### PR DESCRIPTION
**Pull request by ShreyaDhiman24**
## Description
Closes #419 

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [✔️] The app is working correctly after applying the changes.
- [✔️] The app is responsive and displays properly on different screen sizes and devices.
- [✔️] The changes are thoroughly documented in the appropriate files or documentation sections.
- [✔️] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [✔️] I have tested the changes locally and ensured that the app is functioning as expected.
- [✔️] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [✔️] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [✔️] I have followed the coding conventions and style guidelines defined in the project.
- [✔️] I have run the automated tests and all of them pass.
- [✔️] I have considered the performance implications of the changes made.
- [✔️] I have considered the security implications of the changes made.
- [✔️] I have checked for any potential regressions or side effects caused by the changes.
-[✔️]I have performed a self-review of my code.
- [✔️] Starred the repository.
- [ ] Added My Name to the Contributor's List.
-[✔️] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [✔️] I ran the app and tested it locally to verify that it works as expected.

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
@AmanJain18 @anmode

**Comment by Harshil-Jani** [comment]
@ShreyaDhiman24 Can you also resolve conflicts in this PR as well please ?

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24 Can you also resolve conflicts in this PR as well please ?

Yeah sure!

**Comment by Harshil-Jani** [comment]
Hey @ShreyaDhiman24 we are now merging into `develop` branch and there again seems to be a conflict. Apologies for asking to resolve conflicts again. Also for some reason the vercel deployment is failing. Can you check this locally by running `yarn build` or `npm run build`?

**Pull request merged**
