### PR TITLE
Added contact us button for easy navigation and added email validation 

### PR DESCRIPTION
**Pull request by jainmudit68**
## Description

I have added a contact us button in the navbar for easy navigation to the 'connect with us' form.
I have also improved the email validation by adding a RegEx to it.

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [ ] The app is working correctly after applying the changes.
- [ ] The app is responsive and displays properly on different screen sizes and devices.
- [ ] The changes are thoroughly documented in the appropriate files or documentation sections.
- [ ] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [ ] I have tested the changes locally and ensured that the app is functioning as expected.
- [ ] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [ ] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [ ] I have followed the coding conventions and style guidelines defined in the project.
- [ ] I have run the automated tests and all of them pass.
- [ ] I have considered the performance implications of the changes made.
- [ ] I have considered the security implications of the changes made.
- [ ] I have checked for any potential regressions or side effects caused by the changes.
- [ ] I have performed a self-review of my code.
- [ ] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [ ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ ] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)

**email validation**

image
image
image
image
image

**contact us button**

image

## Additional Notes(Optional)

NA
## Related Issues

NA
## Reviewers

Please tag the relevant team members or reviewers who should review this pull request.

### CODE REVIEW

**Comment by anmode** [comment]
could you also fix the form validation? I see form isn't accepting email id

**Comment by jainmudit68** [comment]
> could you also fix the form validation? I see form isn't accepting email id

Could you please elaborate which email id are you trying with! I think some edge cases might be remaining, it would be helpful if you could provide me with your sample

**Review by tusharbansal22 — CHANGES_REQUESTED** [review]
On clicking the 'contact us' button , there should be a scroll effecct just like that in courses section

**Comment by anmode** [comment]
> On clicking the 'contact us' button , there should be a scroll effecct just like that in courses section

+1 and this pR would be merged after https://github.com/amupedia2021/Project-Amupedia/pull/291

**Pull request closed without merging**
