### PR TITLE
Image changes  and wonderful styling has been done by me

### PR DESCRIPTION
**Pull request by MonaMobeen**
hey, I ve  improved html contents in components 
Also improvised image 
Lastly styling changes done by me

### CODE REVIEW

**Comment by MemoonaMobeen** [comment]
**Hey @auempedia accept this and add hacktoberfest label to it**

**Review by MemoonaMobeen — COMMENTED** [review]
hey @amupedia  I have done changes its all fine now
add Hacktoberfest label here

**Comment by MemoonaMobeen** [comment]
hey @amupedia plz accept this request

**Comment by anmode** [comment]
> hey @amupedia plz accept this request

Please resolve the conflict. First

**Comment by MemoonaMobeen** [comment]
> > hey @amupedia plz accept this request
> 
> Please resolve the conflict. First

Okay

**Comment by anmode** [comment]
Heyy! Still, there are conflicts in your branch i can see!

**Comment by anmode** [comment]
You can connect here! We will able to help you https://t.me/+_bLS3xa8rWs3NGJl

**Comment by MemoonaMobeen** [comment]
hey @anmode now there's no conflicts
plz add hacktoberfest label to it

**Comment by anmode** [comment]
> hey @anmode now there's no conflicts
> plz add hacktoberfest label to it

Thanks! Sure

**Review by SayyidMuhammad878 — CHANGES_REQUESTED** [review]
Can you make the public folder outside of the pages folder

**Review by MemoonaMobeen — COMMENTED** [review]
Solved review

**Pull request closed without merging**
